#!/usr/bin/env bash
# This bash script displays "Best School" but "Hi" at the 9th location

index=0

while [ $index -lt 10 ]
do
	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((index++))
done